# This is a basic workflow to help you get started with Actions

name: TF_LINT_SCAN_BROKEN_SYM_LINKS

env:
  ## Sets environment variable
  SOLUBLE_ORG_ID: 900000000000 
  SOLUBLE_API_URL: https://app.demo.soluble.cloud
  SOLUBLE_API_TOKEN: eyJraWQiOiJzand0LWNhMzI5NDFjIiwiYWxnIjoiSFMyNTYifQ.eyJhdWQiOiJ1c2VyIiwiZXhwIjo0MTAyNDQ0ODAwLCJpYXQiOjE2OTE3NzQ3MzEsInN1YiI6InUtYzBlZTg2YTg3MmRjMmRhMyIsIm9yZyI6IjkwMDAwMDAwMDAwMCJ9.BwTKTdxMS1dOJFc1YN63zME1RdiVvIKBMZD0kWuPOmM
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: TF Linting/BrokenSymLinksScan
        run: |
          curl https://raw.githubusercontent.com/soluble-ai/soluble-cli/master/linux-install.sh | sh
          soluble terraform-scan --upload=false
