# This is a basic workflow to help you get started with Actions

name: Testing-14444

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  push-to-Dev:
    runs-on: ubuntu-latest
    steps:
      - uses: lacework/lw-scanner-action@v1.3.0
        name: Scan container image for vulnerabilities using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.lwcs }}
          LW_ACCESS_TOKEN: ${{ secrets._3e4ac213e402c4fe2539b26845fb7fdc }}
          IMAGE_NAME: alpine
          IMAGE_TAG: latest
          SAVE_RESULTS_IN_LACEWORK: true
          SAVE_BUILD_REPORT: true
          BUILD_REPORT_FILE_NAME: myreport.html
